namespace KantanMitsumori.Model.Response
{
    public class EstModelView
    {
        public string? TradeDate { get; set; }
        public string? SalesSum { get; set; }
        public string? EstTanName { get; set; }
        public string? SekininName { get; set; }
        public string? ShopTel { get; set; }
        public string? AAInfo { get; set; }
        public string? FirstRegYm { get; set; }
        public string? CheckCarYm { get; set; }
        public string? NowRun { get; set; }
        public string? Vol { get; set; }
        public string? CarPriceTitle { get; set; }
        public string? DiscountT { get; set; }
        public string? Discount { get; set; }
        public string? OpSpeCialTitle { get; set; }
        public string? DaikoTitle { get; set; }
        public string? TaxInsEquivalentTitle { get; set; }
        public string? TaxName { get; set; }
        public string? CarSaleSumTitle { get; set; }
        public string? SalesSumTitle { get; set; }
        public string? SyakenNewZokT { get; set; }
        public string? SyakenNew { get; set; }
        public string? CarPrice { get; set; }
        public string? SonotaTitle { get; set; }
        public string? Sonota { get; set; }

        public string? CarSum { get; set; }
        public string? TaxInsAll { get; set; }
        public string? TaxInsEquivalentAll { get; set; }
        public string? TaxFreeAll { get; set; }
        public string? TaxCostAll { get; set; }
        public string? ConTax { get; set; }
        public string? CarSaleSum { get; set; }
        public string? TradeInPrice { get; set; }
        public string? Balance { get; set; }
        public string? AutoTaxMonth { get; set; }
        public string? AutoTax { get; set; }
        public string? AutoTaxEquivalent { get; set; }
        public string? AcqTax { get; set; }
        public string? WeightTax { get; set; }
        public string? DamageIns { get; set; }
        public string? DamageInsEquivalent { get; set; }
        public string? DamageInsMonth { get; set; }
        public string? OptionIns { get; set; }
        public string? TaxFreeGarage { get; set; }
        public string? TaxFreeCheck { get; set; }
        public string? TaxFreeTradeIn { get; set; }
        public string? TaxFreeRecycle { get; set; }
        public string? TaxFreeOther { get; set; }
        public string? TaxFreeSet1Title { get; set; }
        public string? TaxFreeSet1 { get; set; }
        public string? TaxFreeSet2Title { get; set; }
        public string? TaxFreeSet2 { get; set; }
        public string? TaxGarage { get; set; }
        public string? TaxCheck { get; set; }
        public string? TaxTradeIn { get; set; }
        public string? TaxDelivery { get; set; }
        public string? TaxRecycle { get; set; }
        public string? TaxOther { get; set; }
        public string? TaxTradeInSatei { get; set; }
        public string? TaxSet1Title { get; set; }
        public string? TaxSet1 { get; set; }
        public string? TaxSet2Title { get; set; }
        public string? TaxSet2 { get; set; }
        public string? TaxSet3Title { get; set; }
        public string? TaxSet3 { get; set; }
        public string? Deposit { get; set; }
        public string? Principal { get; set; }
        public string? PartitionFee { get; set; }
        public string? PartitionAmount { get; set; }
        public string? PayTimes { get; set; }
        public string? Kikan { get; set; }
        public string? FirstPayAmount { get; set; }
        public string? PayAmount { get; set; }
        public string? PayTimes2 { get; set; }
        public string? BonusMonth { get; set; }
        public string? BonusAmount { get; set; }
        public string? BonusTimes { get; set; }
        public string? Rate { get; set; }
        public string? WarningRecalc { get; set; }
        public string? FirstRegistration { get; set; }
        public string? InspectionExpirationDate { get; set; }
        public string? LeaseStartMonth { get; set; }
        public string? LeasePeriod { get; set; }
        public string? LeaseExpirationDate { get; set; }
        public string? MonthlyLeaseFee { get; set; }
        public string? LeaseTotal { get; set; }
        public string? ContractPlanName { get; set; }
        public string? IsExtendedGuarantee { get; set; }
        public string? InsuranceCompanyName { get; set; }
        public string? InsuranceFee { get; set; }
        public string? DownPayment { get; set; }
        public string? IdeTradeInPrice { get; set; }
        public string? TradeInFirstRegYm { get; set; }
        public string? TradeInCheckCarYm { get; set; }
        public string? SitaRun { get; set; }
        public string? TradeInRegNo { get; set; }
        public string? Notes { get; set; }

        #region Option
     
        public string? OptionPrice1 { get; set; }    
        public string? OptionPrice2 { get; set; }     
        public string? OptionPrice3 { get; set; }      
        public string? OptionPrice4 { get; set; }     
        public string? OptionPrice5 { get; set; }     
        public string? OptionPrice6 { get; set; }      
        public string? OptionPrice7 { get; set; }    
        public string? OptionPrice8 { get; set; }      
        public string? OptionPrice9 { get; set; }    
        public string? OptionPrice10 { get; set; }    
        public string? OptionPrice11 { get; set; }     
        public string? OptionPrice12 { get; set; }
        public string? OptionPriceAll { get; set; }
        #endregion option
    }
}