namespace KantanMitsumori.Model
{
    public class EstimateModelView
    {
        public string dspEstNo { get; set; }
        public string dspTradeDate { get; set; }
        public string csvTradeDate { get; set; }
        public string dspCarName { get; set; }
        public string csvMakerName { get; set; }
        public string csvModelName { get; set; }
        public string dspGradeName { get; set; }
        public string dspCase { get; set; }
        public string dspChassisNo { get; set; }
        public string dspFirstRegYm { get; set; }
        public string csvFirstRegYm { get; set; }
        public string dspCheckCarYm { get; set; }
        public string csvCheckCarYm { get; set; }
        public string dspNowOdometer { get; set; }
        public string dspDispVol { get; set; }
        public string dspMission { get; set; }
        public string dspAccidentHis { get; set; }
        public string dspBusinessHis { get; set; }
        public string dspEquipment { get; set; }
        public string dspBodyColor { get; set; }
        public string dspCarImgPath { get; set; }
        public string dspTotalCost { get; set; }
        public string dspCarPrice { get; set; }
        public string dspDiscountT { get; set; }
        public string dspDiscount { get; set; }
        public string dspNouCost { get; set; }
        public string dspSyakenNewZokT { get; set; }
        public string dspSyakenNewZokTc { get; set; }
        public string dspSyakenNew { get; set; }
        public string dspSyakenZok { get; set; }
        public string dspCarSum { get; set; }
        public string dspOptionInputKb { get; set; }
        public string dspOptionName1 { get; set; }
        public string dspOptionPrice1 { get; set; }
        public string dspOptionName2 { get; set; }
        public string dspOptionPrice2 { get; set; }
        public string dspOptionName3 { get; set; }
        public string dspOptionPrice3 { get; set; }
        public string dspOptionName4 { get; set; }
        public string dspOptionPrice4 { get; set; }
        public string dspOptionName5 { get; set; }
        public string dspOptionPrice5 { get; set; }
        public string dspOptionName6 { get; set; }
        public string dspOptionPrice6 { get; set; }
        public string dspOptionName7 { get; set; }
        public string dspOptionPrice7 { get; set; }
        public string dspOptionName8 { get; set; }
        public string dspOptionPrice8 { get; set; }
        public string dspOptionName9 { get; set; }
        public string dspOptionPrice9 { get; set; }
        public string dspOptionName10 { get; set; }
        public string dspOptionPrice10 { get; set; }
        public string dspOptionName11 { get; set; }
        public string dspOptionPrice11 { get; set; }
        public string dspOptionName12 { get; set; }
        public string dspOptionPrice12 { get; set; }
        public string dspOptionPriceAll { get; set; }
        public string dspTaxInsInputKb { get; set; }
        public string dspAutoTax { get; set; }
        public string dspAcqTax { get; set; }
        public string dspWeightTax { get; set; }
        public string dspDamageIns { get; set; }
        public string dspOptionIns { get; set; }
        public string dspTaxInsAll { get; set; }
        public string dspTaxFreeKb { get; set; }
        public string dspTaxFreeGarage { get; set; }
        public string dspTaxFreeCheck { get; set; }
        public string dspTaxFreeTradeIn { get; set; }
        public string dspTaxFreeRecycle { get; set; }
        public string dspTaxFreeOther { get; set; }
        public string dspTaxFreeAll { get; set; }
        public string dspTaxCostKb { get; set; }
        public string dspTaxGarage { get; set; }
        public string dspTaxCheck { get; set; }
        public string dspTaxTradeIn { get; set; }
        public string dspTaxDelivery { get; set; }
        public string dspTaxRecycle { get; set; }
        public string dspTaxOther { get; set; }
        public string dspTaxCostAll { get; set; }
        public string dspTaxName { get; set; }
        public string dspConTax { get; set; }
        public string dspCarSaleSum { get; set; }
        public string dspCarSaleSumTitle { get; set; }
        public string dspTradeInCarName { get; set; }
        public string dspTradeInFirstRegYm { get; set; }
        public string csvTradeInFirstRegYm { get; set; }
        public string dspTradeInCheckCarYm { get; set; }
        public string csvTradeInCheckCarYm { get; set; }
        public string dspTradeInNowOdometer { get; set; }
        public string dspTradeInRegNo { get; set; }
        public string dspTradeInChassisNo { get; set; }
        public string dspTradeInBodyColor { get; set; }
        public string dspTradeInPrice { get; set; }
        public string dspBalanceT { get; set; }
        public string dspBalance { get; set; }
        public string dspSalesSum { get; set; }
        public string dspCustKName { get; set; }
        public string dspRate { get; set; }
        public string csvRate { get; set; }
        public string dspDeposit { get; set; }
        public string dspPrincipal { get; set; }
        public string dspPartitionFee { get; set; }
        public string dspPartitionAmount { get; set; }
        public string dspPayTimes { get; set; }
        public string dspPayTimes2 { get; set; }
        public string dspKikan { get; set; }
        public string csvFirstPayMonth { get; set; }
        public string csvLastPayMonth { get; set; }
        public string dspFirstPayAmount { get; set; }
        public string dspPayAmount { get; set; }
        public string dspBonusAmount { get; set; }
        public string dspBonusMonth { get; set; }
        public string csvBonusFirst { get; set; }
        public string csvBonusSecond { get; set; }
        public string dspBonusTimes { get; set; }
        public string dspShopNm { get; set; }
        public string dspShopAdr { get; set; }
        public string csvShopTel { get; set; }
        public string csvShopTanName { get; set; }
        public string dspEstTanName { get; set; }
        public string dspAAYear { get; set; }
        public string dspAAHyk { get; set; }
        public string dspAAPrice { get; set; }
        public string dspSirPrice { get; set; }
        public string csvRakuSatu { get; set; }
        public string csvRikusou { get; set; }
        public string dspAAPlace { get; set; }
        public string dspAANo { get; set; }
        public string dspAATime { get; set; }
        public string dspAutoTaxMonth { get; set; }
        public string csvAutoTaxMonth { get; set; }
        public string dspDamageInsMonth { get; set; }
        public string csvDamageInsMonth { get; set; }
        public string dspTaxTradeInSatei { get; set; }
        public string dspTaxSet1Title { get; set; }
        public string dspTaxSet1 { get; set; }
        public string dspTaxSet2Title { get; set; }
        public string dspTaxSet2 { get; set; }
        public string dspTaxSet3Title { get; set; }
        public string dspTaxSet3 { get; set; }
        public string dspTaxFreeSet1Title { get; set; }
        public string dspTaxFreeSet1 { get; set; }
        public string dspTaxFreeSet2Title { get; set; }
        public string dspTaxFreeSet2 { get; set; }
        public string dspCustMemo { get; set; }
        public string dspAAInfo { get; set; }
        public string dspSonotaTitle { get; set; }
        public string dspSonota { get; set; }
        public string dspTradeInUM { get; set; }
        public string dspCarImgPath1 { get; set; }
        public string dspCarImgPath2 { get; set; }
        public string dspCarImgPath3 { get; set; }
        public string dspCarImgPath4 { get; set; }
        public string dspCarImgPath5 { get; set; }
        public string dspCarImgPath6 { get; set; }
        public string dspCarImgPath7 { get; set; }
        public string dspCarImgPath8 { get; set; }
        public string dspNotes { get; set; }
        public string dspAutoTaxEquivalent { get; set; }
        public string dspDamageInsEquivalent { get; set; }
        public string dspTaxInsEquivalentAll { get; set; }
        public string dspSalesSumTitle { get; set; }
        public string dspCarPriceTitle { get; set; }
        public string dspOpSpeCialTitle { get; set; }
        public string dspTaxInsEquivalentTitle { get; set; }
        public string dspDaikoTitle { get; set; }
        public string dspDispVolUnit { get; set; }
        public string dspMilUnit { get; set; }
        public string dspTradeInMilUnit { get; set; }
        public string dspSekininName { get; set; }
        public string dspShopTel { get; set; }
        public string csvSekininName { get; set; }
        public string dspLeaseFlag { get; set; }
        public long dspLeaseTargetRestriction { get; set; }
    }
}
